- test/test_predictive_control.jl
`ared` is a lower-level function that belongs to MatrixEquations.jl, and this function has a different signature where the control penalty matrix comes before the state matrix. This PR changes to use the `are` function exported by ControlSystems to make the call correct, and changes the test tolerance to be stricter since we now actually solve the correct problem :)
> fix wrong function signature ared

- .github/workflows/CI.yml
- docs/src/internals/sim_model.md
- docs/src/internals/state_estim.md
- src/controller/execute.jl
- src/estimator/execute.jl
- src/estimator/internal_model.jl
- src/estimator/kalman.jl
- src/estimator/mhe/execute.jl
- src/model/linearization.jl
- src/model/linmodel.jl
- src/model/nonlinmodel.jl
- src/plot_sim.jl
- src/precompile.jl
- src/sim_model.jl
- src/state_estim.jl
- test/test_predictive_control.jl
- test/test_sim_model.jl
Added: support with mutating `f!`and `h!` functions to reduce the allocations. This change is backward compatible since non-mutating functions are also supported and the syntax is identical to previous version of the package.
> Added: mutating `NonLinModel`

- Project.toml
- docs/src/manual/nonlinmpc.md
- src/estimator/kalman.jl
- src/estimator/mhe/construct.jl
- src/estimator/mhe/execute.jl
Changed: MHE now defaults to `UnscentedKalmanFilter` for arrival covariance estimate of `NonLinModel` (instead of EKF)
> Added: MHE supports custom estimator for the arrival covariance

- src/controller/execute.jl
- src/estimator/execute.jl
- src/predictive_control.jl
- src/sim_model.jl
- src/state_estim.jl
I now use `model.dop` as default `d` value in all the methods. This does not allocate. As a minor drawback, no error is raised if the user construct a controller with a feedforward compensation but does not provide a `d` argument in `moveinput!` (an error was raised before).
> Reduce allocations by avoiding `empty` for default `d` argument

- src/controller/execute.jl
- src/estimator/execute.jl
- src/estimator/internal_model.jl
- src/estimator/kalman.jl
- src/estimator/luenberger.jl
- src/estimator/mhe/construct.jl
- src/model/linmodel.jl
- src/model/nonlinmodel.jl
- src/plot_sim.jl
- src/predictive_control.jl
- src/sim_model.jl
- src/state_estim.jl
default `d` argument is now `buffer.empty`
(restore the error handling when no d is provided)
> added: `SimModelBuffer` and `StateEsimatorBuffer` objects to reduce the allocations

- Project.toml
- README.md
- docs/src/manual/nonlinmpc.md
- src/controller/construct.jl
- src/estimator/construct.jl
- src/estimator/execute.jl
- src/estimator/internal_model.jl
- src/estimator/kalman.jl
- src/estimator/luenberger.jl
- src/estimator/mhe/construct.jl
- src/estimator/mhe/execute.jl
- src/state_estim.jl
`SteadyKalmanFilter`, `Luenberger`, `KalmanFilter` and `UnscentedKalmanFilter` are all 0 allocation for `preparestate!` and `updatestate!` functions
> added: doc correction and reduce allocations for all Kalman filters

- README.md
- docs/src/public/generic_func.md
- src/ModelPredictiveControl.jl
- src/controller/execute.jl
- src/estimator/execute.jl
- src/model/linmodel.jl
- src/model/nonlinmodel.jl
- src/sim_model.jl
- test/test_predictive_control.jl
- test/test_sim_model.jl
- test/test_state_estim.jl
> Added: soft real time utilities

- docs/src/manual/nonlinmpc.md
- src/model/linearization.jl
- src/sim_model.jl
forgot to add it in some docstrings
> doc: add the parameter `p` in f and h function signature

- docs/src/manual/nonlinmpc.md
- docs/src/public/plot_sim.md
- src/plot_sim.jl
This PR tries to solve #119 
`RecipesBase.plot` is the function that is actually called when plotting a result object, `ModelPredictiveControl.plot` is a different function with the same name (in another namespace), causing some confusion
> Avoid introducing MPC.plot

- Project.toml
- src/controller/construct.jl
- src/controller/execute.jl
- src/controller/explicitmpc.jl
- src/controller/linmpc.jl
- src/controller/nonlinmpc.jl
- src/predictive_control.jl
- test/test_predictive_control.jl
`ControllerConstraint{NT}` is no longer concrete
`ControllerConstraint{NT, GCfunc}` is
> Fix type instability in `LinMPC` and `NonLinMPC` (introduced in 1.1.0) 

- src/controller/construct.jl
- src/controller/execute.jl
- src/controller/nonlinmpc.jl
After some real benchmarking, the `noR̂u` field was useful to save some computations
So I added similar information for the 4 weights
> Added: `iszero_W` field in for the 4 weights in `ControllerWeights` struct

- Project.toml
- src/controller/execute.jl
- src/controller/explicitmpc.jl
- src/controller/nonlinmpc.jl
- src/estimator/mhe/construct.jl
- src/model/solver.jl
- forcing specialization in the NLP functions by using `Vararg{T, N}` instead of splatting (see this [tip](https://docs.julialang.org/en/v1/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing))
- skipping computations in `extended_predictions` when possible
- also improved code reuse in the NLP functions to improve code maintainability
> Added: slightly speed up `NonLinMPC` and `MovingHorizonEstimator` 

- Project.toml
- src/controller/execute.jl
- src/estimator/luenberger.jl
- src/estimator/mhe/construct.jl
- src/estimator/mhe/execute.jl
- src/general.jl
- test/test_state_estim.jl
context: See https://github.com/JuliaControl/ModelPredictiveControl.jl/issues/98#issuecomment-2607640393 point 1.
> debug: fallback if `MovingHorizonEstimator` arrival covariance update fails

- .github/workflows/CI.yml
- src/estimator/mhe/execute.jl
- test/test_state_estim.jl
Following the "convention" throughout the package, a non fatal `@error` log make more sense than `@warn`. 
It's similar to `@error` emitted by an unfeasible MPC problem: something is wrong but there is a fallback. That is, take the solution from the last time step.
Also updated the `CI.yml` with new feature like improved speed with cache v2 and replacing Julia nightly by `pre` testing.
> changed: `@error` instead of `@warn` in MHE arrival covariance fallback + update CI

- src/estimator/mhe/execute.jl
- test/test_state_estim.jl
The fallback is still relevant if new `NaN` or `Inf` values appear in the covariance arrival. It just happens in CI (a NaN value was produced by the `cholesky` calls)
A different message is print tho to help troubleshooting. Since as mentioned by @baggepinnen, it may be caused by a different issue, like a sudden NaN values in the measurements `ym`.
> debug: fallback if nonfinite arr. cov. after correction/update

- Project.toml
- src/model/linearization.jl
- src/model/nonlinmodel.jl
- src/sim_model.jl
This reverts commit 25865eacc5486a19b1682eda5ef3923d10174285. (so `linearize!` is no longer allocation-free)
*MOTIVE*
The intricate solution with a `struct` and 5 separate closures creates a weird type-instability on `NonLinModel` when its `f` and `h` functions are not in the global scope. I'm not sure I fully understand why.
In the end I prefer some small but deterministic allocations in `ForwardDiff.jacobian!` than a type-instability. I also benchmarked the two implementations, and the small allocations are way more performant than the type-instable version.
> debug: revert allocation-free `linearize!` to avoid `NonLinModel` type-instability

- Project.toml
- src/model/linmodel.jl
- src/sim_model.jl
Not proud of this but I forgot to remove a struct parameter in `SimModelBuffer` in last release. As a result, the `buffer` field in `NonLinModel` was an abstract type, instead of a fully defined concrete type, as it should be.
Yep similar mistake as before! :cry: 
I need to find the time to implement some `JET.jl` tests for type stability and such.
> debug: `NonLinModel` fields are now all concrete types

- Project.toml
- src/general.jl
- src/model/linearization.jl
- src/model/nonlinmodel.jl
- src/sim_model.jl
- test/1_test_sim_model.jl
- test/4_test_plot_sim.jl
Re-designed the Jacobian and linearization buffers for an implementation that is a bit simpler, cleaner and also modular (will also work with gradients and hessians, normally)
Also prepare the ground for migration to `DifferentiationInterface.jl`.
There is no type-instability at runtime, tested on my side with `@code_warntype`.
Related to #162
> added: `linearize!` is allocation-free once again

- src/controller/execute.jl
It was the MHE message (a copy-paste mistake)
> debug: correct `@error` msg for MPC not solved

- Project.toml
- src/controller/nonlinmpc.jl
- src/controller/transcription.jl
- src/estimator/mhe/construct.jl
- src/general.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
One big step further toward integration of `DifferentiationInterface.jl`
Related to #162 
The splatting syntax of `JuMP` forces us to compute the Jacobians of the constraints as a combination of multiple gradients (concatenated as a Jacobian).
This means that the `jacobian` function of the AD tool (dense `ForwardDiff.jl`, for now) were called redundantly `ng` and `neq` times for a specific decision vector value `Z̃` (where `ng` and `neq` is the respective number of nonlinear inequality and equality constraints). This is wasteful. A caching mechanism was implemented to store the Jacobians of the constraints and reuse them when needed. 
The performance improvement is about 5-10x faster now on `NonLinMPC` with `NonLinModel`. Note that it only applies when nonlinear constraints are present …
> Changed: major NLP refactoring for flexibility and significantly improve performance

- src/controller/nonlinmpc.jl
- src/estimator/mhe/construct.jl
- src/plot_sim.jl
- src/sim_model.jl
- test/1_test_sim_model.jl
- test/4_test_plot_sim.jl
The `x_noise` keyword argument of `sim!` now works. It also deprecates:
```julia
preparestate!(model::SimModel, ym, d=[])
```
and replace it with:
```julia
preparestate!(model::SimModel)
```
The old method with `ym` and `d` arguments still works but it's now deprecated with `Base.depwarn`. The old method was not making sense since the two arguments were ignored. Moreover, it's now consistent with the `updatestate!` generic function, that is, it receives no measurement as argument for `SimModel`.
> Debug `x_noise` argument in `sim!` and deprecate `preparestate!(::SimModel, _ , _ )`

- Project.toml
- src/controller/nonlinmpc.jl
- src/controller/transcription.jl
- test/3_test_predictive_control.jl
I forgot that I need a new dispatch in `con_nonlinprog!` function, since the terminal constraints are linear for `NonLinModel` + `MultipleShooting`, thus they do not appear in this function (they are in the linear inequality constraint matrix)
Added some new constraint violation tests to cover this specific case.
> Debug: ineq. constraint for `NonLinModel` and `MultipleShooting`

- README.md
- docs/src/index.md
- src/controller/transcription.jl
- src/estimator/execute.jl
- src/estimator/kalman.jl
- src/estimator/mhe/execute.jl
- src/model/linearization.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
Following #179, also migrates `ExtendedKalmanFilter` to DI.jl. There is a new `jacobian` keyword arguments to swap the backend.
Bonus: the estimator is now allocation-free at runtime (at least with `AutoForwardDiff`)
> Added: `ExtendedKalmanFilter` now uses `DifferentiationInterface.jl` + now allocation-free

- Project.toml
- src/controller/execute.jl
- src/controller/transcription.jl
- src/estimator/mhe/execute.jl
- src/model/linearization.jl
- src/plot_sim.jl
- test/1_test_sim_model.jl
some backend works with empty matrices (e.g. `AutoForwardDiff`) others not (e.g. : `AutoFiniteDiff`)
closes #185
> debug: do not call `jacobian!` if `nd==0` in `linearize`

- .github/workflows/CI.yml
- src/model/linearization.jl
- test/1_test_sim_model.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
I choose to use the builtin `@allocations` macro for two reasons:
1) no additional test depedency (e.g. BechmarkTools)
2) it's faster than `@ballocations` in BechmarkTools
As a drawback there is known limitations (or feature? :smile:) for exemple https://github.com/JuliaLang/julia/issues/51112. A simple workaround for this specific issue is to create another function that calls the tested in-place function and returns `nothing`:
```julia
using Test
function myfunc2!(arg1, arg2)
myfunc!(arg1, arg2)
return nothing
end
@test @allocations(myfunc2!(arg1, arg2)) == 0
```
It seems to work well on Julia 1.11.
> Test: added allocations tests for types that are known to be allocation-free (SKIP THEM FOR NOW)

- Project.toml
- src/estimator/execute.jl
- src/model/linmodel.jl
- test/0_test_module.jl
- test/1_test_sim_model.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
Following the discussion [here](https://github.com/JuliaControl/ControlSystems.jl/commit/a1412604c340ec735bd40291e540dc6672cee009#commitcomment-155584728), the test are adapted to always expect a different state-space realization if the `LinModel` outer constructor is used.
> test: adapt tests for the new automatically balancing `minreal` function

- Project.toml
- src/estimator/execute.jl
- src/estimator/kalman.jl
- src/model/linmodel.jl
- test/0_test_module.jl
- test/1_test_sim_model.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
Some matrix products were computed on normal dense matrix using `M.data` instead of `M`, in which `M isa Hermitian`. It was because of a bug in `LinearAlgebra` that produces a dynamic dispatch (https://github.com/JuliaLang/julia/issues/53951). This bug is solved now so it's no longer needed. 
It's also not the best idea for the numerical stability since covariance matrices are `Hermitian`s, and the intermediate matrices in the computation should all be Hermitians also for the consistency.
@1-bart-1 This branch solve the `cholesky!` issue in your exemple on my computer. Give it a try.
I did not try the Joseph form equation here since the `.data` was just bad for the numerical stability, and simply removing that solve the problem. After I merge these changes, If you have any other similar …
> debug: remove `.data` in `KalmanFilter` matrix products

- .github/workflows/CI.yml
- src/controller/execute.jl
- src/estimator/execute.jl
- src/estimator/internal_model.jl
- src/estimator/luenberger.jl
- src/estimator/mhe/execute.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
We can now set the current estimation error covariance `P̂` with the two `setstate!` methods:
```julia
setstate!(estim::StateEstimator, x̂, P̂=nothing)
setstate!(mpc::PredictiveController, x̂, P̂=nothing)
```
The matrix can be modified if `estim` is a:
- `KalmanFilter`
- `UnscentedKalmanFilter`
- `ExtendedKalmanFilter`
The two methods will throw an error if `estim` does not compute this matrix and `P̂ != nothing`, that is for:
- `SteadyKalmanFilter`
- `Luenberger`
- `InternalModel` 
- `MovingHorizonEstimator` (only the estimation covariance at arrival is computed for the MHE, the current covariance is not available)
Also updated codecov github action to v5 in `CI.yml`
> added: `setstate!` now allows estimation covariance `P̂` modification (if applicable)

- Project.toml
- docs/make.jl
- docs/src/internals/predictive_control.md
- docs/src/internals/state_estim.md
- src/ModelPredictiveControl.jl
- src/controller/nonlinmpc.jl
- src/estimator/mhe/construct.jl
This theoretically more efficient than calling the objective/constraint functions and `DI.jacobian!`/`DI.gradient!` separately. For `AutoForwardDiff` backend, this feature is similar to [DiffResult.jl](https://github.com/JuliaDiff/DiffResults.jl).
> Added: `NonLinMPC` and `MovingHorizonEstimator` now use `value_and_gradient!`/`jacobian!` of DI.jl

- Project.toml
- docs/Project.toml
Test locally with DAQP.jl v0.7.1 and everything passes.
> changed: compat of `DAQP` to `0.6, 0.7.1`

- Project.toml
- docs/src/internals/state_estim.md
- src/controller/nonlinmpc.jl
- src/controller/transcription.jl
- src/estimator/internal_model.jl
- src/estimator/mhe/construct.jl
- src/estimator/mhe/execute.jl
- test/2_test_state_estim.jl
In some corner cases (e.g. when `nint_u≠0`, not sure why I did not see this bug when `nint_ym≠0`), the caching of the gradient and jacobian `MovingHorizonEstimator` NLP problem was not working well at the beginning (when the measurement window is not filled, or $N_k \ne H_e$). I added a hack with a clever warm-starting to force the update of the gradient/jacobian when the window is not filled.
Note that it's impossible to shrink the decision variable vector `Z̃`  in `JuMP.jl`, AFAIK. That would be the cleanest solution  when the window is not filled (at the beginning). My workaround is to "ignore" some decision variable in `Z̃` in the cost and constraint functions at the beginning (for the NLP case, not QP). That is why this clever hack work.
I will add a test for this bug.
> debug: force update of gradient/jacobian in `MovingHorzionEstimator` when window not filled

- docs/src/public/state_estim.md
- src/ModelPredictiveControl.jl
- src/controller/construct.jl
- src/controller/explicitmpc.jl
- src/controller/linmpc.jl
- src/estimator/kalman.jl
- src/estimator/manual.jl
- src/model/nonlinmodel.jl
- src/state_estim.jl
This new `StateEstimator` type enables two new features:
1. using linear predictive controller with a nonlinear state estimator, to improve the accuracy of the state estimate
2. using predictive controller of this package with a state estimator from another package, for example [LowLevelParticleFilters.jl](https://github.com/baggepinnen/LowLevelParticleFilters.jl).
> added: `ManualEstimator` to turn off built-in state estimation

- docs/src/internals/predictive_control.md
- docs/src/public/state_estim.md
- src/ModelPredictiveControl.jl
- src/controller/construct.jl
- src/controller/execute.jl
- src/controller/explicitmpc.jl
- src/controller/linmpc.jl
- src/controller/nonlinmpc.jl
- src/controller/transcription.jl
- src/estimator/execute.jl
- src/estimator/internal_model.jl
- src/estimator/kalman.jl
- src/estimator/luenberger.jl
- src/estimator/manual.jl
- src/estimator/mhe/execute.jl
- src/model/nonlinmodel.jl
- src/state_estim.jl
- test/2_test_state_estim.jl
- test/3_test_predictive_control.jl
The field,  corresponding to $\mathbf{u_0}(k-1) = \mathbf{u}(k-1) - \mathbf{u_{op}}$, is only used in the controller to convert input increments $\mathbf{\Delta U}$ to inputs $\mathbf{U}$. It is never used in the state estimators so it don't really belong there (except in the MHE, in which I left it there). It's cleaner like this and it slightly simplifies the API for the upcoming `ManualEstimator`.
> changed: moved `lastu0` inside `PredictiveController` objects

- src/estimator/mhe/construct.jl
- src/estimator/mhe/execute.jl
- src/general.jl
- test/2_test_state_estim.jl
Allocation-free methods with `LinearAlgebra` standard types (and numerically robust since it relies on a cholesky factorization, knowing that covariance matrices are positive definite Hermitian matrices).
There is also a fallback method with other `AbstractMatrix` with some allocations.
Thanks to <https://discourse.julialang.org/t/non-allocating-matrix-inversion/62264/14?u=franckgaga> for the idea.
> added: `inv!` for `MovingHorizonEstimator` covariance matrices

- src/controller/construct.jl
- src/controller/explicitmpc.jl
- src/controller/linmpc.jl
- src/controller/nonlinmpc.jl
- src/general.jl
- test/3_test_predictive_control.jl
Constructing with e.g.:
```julia
mpc = LinMPC(model, M_Hp=Hermitian(diagm(ones(10)))
```
was crashing.  I added generic dispatch to convert correctly and handle all matrix types correctly.
> debug: support `Hermitian` weights in `PredictiveController`

- docs/src/internals/state_estim.md
- src/estimator/construct.jl
- src/estimator/execute.jl
- src/estimator/kalman.jl
It needs to be clarified, since the upcoming collocation methods will separate the deterministic and stochastic states in the equality constraints.
> doc: clarifying model augmentation for `NonLinMPC` in `f̂!` docstring

- Project.toml
- README.md
- docs/src/internals/predictive_control.md
- docs/src/internals/state_estim.md
- src/controller/transcription.jl
- src/estimator/construct.jl
- src/estimator/execute.jl
- src/estimator/mhe/execute.jl
Added the prediction and defect equations for all the transcription in `Internals -> Predictive Controllers` section.
This is mainly for developper (myself 🤣), since it will be helpful for implementing more complex collocation methods.
> doc: describing the internal of the various prediction and transcription methods

- src/controller/transcription.jl
- test/3_test_predictive_control.jl
The default is still `h=0`, that is zero-order hold, like all the other `DiffSolver` in the package. 
Added a comments in `TrapezoidalCollocation` docstring that there will be an assumption mismatch between `TrapezoidalCollocation(1)` and a plant model simulated with the various `DiffSolver` in the package.
Also added some `moveinput!` simple tests using `TrapezoidalCollocation(1)`
> added: piecewise linear manipulated inputs with `TrapezoidalCollocation(1)`

- Project.toml
- src/controller/construct.jl
- src/controller/explicitmpc.jl
- src/controller/linmpc.jl
- src/controller/nonlinmpc.jl
- src/estimator/internal_model.jl
- src/estimator/kalman.jl
- src/estimator/luenberger.jl
- src/estimator/manual.jl
- src/estimator/mhe.jl
- src/estimator/mhe/construct.jl
- src/estimator/mhe/execute.jl
- src/general.jl
- src/model/linmodel.jl
- src/model/nonlinmodel.jl
- src/predictive_control.jl
- src/sim_model.jl
- src/state_estim.jl
This is a preview of the new printed string:
```
NonLinMPC controller with a sample time Ts = 0.1 s:
├ estimator: UnscentedKalmanFilter
├ model: NonLinModel
├ optimizer: Ipopt 
├ transcription: TrapezoidalCollocation
├ gradient: AutoForwardDiff
├ jacobian: AutoSparse (AutoForwardDiff, TracerSparsityDetector, GreedyColoringAlgorithm)
└ dimensions:
├ 20 prediction steps Hp
├  2 control steps Hc
├  0 slack variable ϵ (control constraints)
├  1 manipulated inputs u (1 integrating states)
├  3 estimated states x̂
├  1 measured outputs ym (0 integrating states)
├  0 unmeasured outputs yu
└  0 measured disturbances d
```
The `NonLinModel`, `ExtendedKalmanFilter`, `MovingHorizonEstimator` and `NonLinMPC` now also print the differentiation backends.
I also renamed $\epsilon$ to $\varepsilon$ for …
> added: clearer pretty-print with trees + print differentiation backends

- docs/src/manual/nonlinmpc.md
- src/model/linmodel.jl
- src/model/nonlinmodel.jl
Also substituted $\mathbf{z}(t)$ to $\mathbf{s}(t)$ to avoid confusion with the decision variables
> doc: details on proper systems in `LinModel` extended help

- Project.toml
- benchmark/3_bench_predictive_control.jl
- src/controller/transcription.jl
- src/estimator/internal_model.jl
- src/general.jl
- test/3_test_predictive_control.jl
There are two new keyword arguments in `MultipleShooting` and `TrapezoidalCollocation` constructors:
-  `f_threads=false`: to multithread the defect of the states in the equality constraints for `NonLinModel` (worthy only when $\mathbf{f}$ is expensive to evaluate)
-  `h_threads=false`: to multithread the output functions (worthy only when $\mathbf{h}$ is expensive to evaluate)
It's not common that $\mathbf{h}$ is expensive to evaluate but the option is still there in such cases. Note that as mentionned [here](https://github.com/JuliaControl/ModelPredictiveControl.jl/issues/257#issuecomment-3309578699), it's impossible to use the efficient $\mathbf{f}$-call  tricks with multithreading, even with `h=1`. I added some `if`s to correctly handle multi-threading with `h=1`.
> added: multithreading with `MultipleShooting` and `TrapezoidalCollocation`

- src/controller/construct.jl
- src/controller/nonlinmpc.jl
It does make sense to test the condition number of the Hessian if there is no custom objective function, but otherwise it does not make sense.
> debug: do not warn `cond(H̃)` in `NonLinMPC` if `Ewt≠0`
